openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    Server for storaging contacts
tags:
  - name: Main
    description: Main endpoint
  - name: Auth
    description: Authentication endpoints
  - name: Contacts
    description: Contacts endpoints
servers:
  - url: http://localhost:3000
  - url: https://homework-7.onrender.com/
paths:
  /:
    get:
      $ref: '../swagger/paths/main/get.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register/post.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh/post.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd/post.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
